name: Update Badges
on:
  schedule:
    # Runs daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allows manual runs
jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants permission for the action to write to the README
    steps:
      - name: Update Badges
        uses: pemtajo/badge-readme@main
        with:
          CREDILLY_USER: ${{ github.actor }} # Uses your GitHub username
          
